// CopyrightCopyright (c) GDFrank
// SPDX-License-Identifier: MIT

namespace Source77NW
{
    /// <summary>
    /// Common UI/message words (buttons, menus, status, issue text) as an
    /// EnumCodes-driven enum, so each word's caption can carry a
    /// culture/lingo override via ResCode.
    /// </summary>
    /// <remarks>
    /// Member names ARE the default captions (EnumCodes NameAsCaption);
    /// a registered lingo pack overrides them per language. Values are
    /// explicit bytes; per-member docs are intentionally omitted - the
    /// names are self-evident.
    /// </remarks>
    [EnumCodes]
    public enum WordId : byte
    {
        And = 0,
        Any = 1,
        As = 2,
        Audio = 3,
        Audios = 4,
        Bigger = 5,
        Cancel = 6,
        Canceled = 7,
        Canceling = 8,
        Clipboard = 9,
        Close = 10,
        Closed = 11,
        Completed = 12,
        Contains = 13,
        Content = 14,
        Contents = 15,
        Continue = 16,
        Copied = 17,
        Copy = 18,
        Count = 19,
        Create = 20,
        Created = 21,
        Critical = 22,
        Date = 23,
        Default = 24,
        Definition = 25,
        Delete = 26,
        Deleted = 27,
        Directory = 28,
        Disable = 29,
        Disabled = 30,
        Done = 31,
        Echo = 32,
        Echos = 33,
        Edit = 34,
        Else = 35,
        Enable = 36,
        Enabled = 37,
        Enum = 38,
        Exit = 39,
        Expecting = 40,
        Fail = 41,
        Failed = 42,
        Failure = 43,
        False = 44,
        File = 45,
        Finished = 46,
        Fix = 47,
        Fixed = 48,
        Folder = 49,
        Folders = 50,
        Font = 51,
        Fonts = 52,
        For = 53,
        From = 54,
        Hello = 55,
        Help = 56,
        Hide = 57,
        Home = 58,
        If = 59,
        Ignore = 60,
        Ignored = 61,
        Image = 62,
        Images = 63,
        In = 64,
        Input = 65,
        Invalid = 66,
        Issue = 67,
        Issues = 68,
        Item = 69,
        Job = 70,
        Key = 71,
        Length = 72,
        Log = 73,
        Maybe = 74,
        Media = 75,
        Menu = 76,
        Missing = 77,
        Move = 78,
        Moved = 79,
        Name = 80,
        Named = 81,
        No = 82,
        None = 83,
        Nosuch = 84,
        Nothing = 85,
        Off = 86,
        OK = 87,
        On = 88,
        OP = 89,
        Open = 90,
        Opened = 91,
        Operand = 92,
        Operator = 93,
        Or = 94,
        Otherwise = 95,
        Out = 96,
        Output = 97,
        Path = 98,
        Permit = 99,
        Play = 100,
        Played = 101,
        Playing = 102,
        Processed = 103,
        Processing = 104,
        Recycle = 105,
        Remove = 106,
        Removed = 107,
        Rename = 108,
        Renamed = 109,
        Replace = 110,
        Replaced = 111,
        Required = 112,
        Requires = 113,
        Reset = 114,
        Resize = 115,
        Resized = 116,
        Rotate = 117,
        Rotated = 118,
        Running = 119,
        Set = 120,
        Settings = 121,
        Size = 122,
        Smaller = 123,
        Source = 124,
        Specified = 125,
        Start = 126,
        Starting = 127,
        Stop = 128,
        Stopping = 129,
        Stream = 130,
        Succeeded = 131,
        Success = 132,
        Summary = 133,
        Target = 134,
        Task = 135,
        Text = 136,
        That = 137,
        Then = 138,
        This = 139,
        Thus = 140,
        Time = 141,
        Timedout = 142,
        To = 143,
        Token = 144,
        True = 145,
        Unspecified = 146,
        Unzipping = 147,
        Update = 148,
        Updated = 149,
        Video = 150,
        Videos = 151,
        View = 152,
        Yes = 153,
        Zip = 154,
        Zipped = 155,
        Zipping = 156,
        Zoom = 157,
    }
}
